Wrapped vimmer in function.
Signed-off-by: Ross Hadden <rosshadden@gmail.com>

diff --git a/bin/vimmer b/bin/vimmer
--- a/bin/vimmer
+++ b/bin/vimmer
@@ -1,29 +1,42 @@
 #!/usr/bin/env bash
 
+# TODO: figure out how to set this in i3 instead
+export EDITOR=nvim
+
 if ! [ -x "$(command -v vipe)" ]; then
-  echo "Error: vipe not found." >&2
-  exit 1
+	echo "Error: vipe not found." >&2
+	exit 1
 fi
 
 if ! [ -x "$(command -v xsel)" ]; then
-  echo "Error: xsel not found." >&2
-  exit 1
+	echo "Error: xsel not found." >&2
+	exit 1
 fi
-
-# TMP=$(mktemp -p /tmp -t vimclip.XXXXXXXX)
-# $EDITOR +"w! $TMP"
-# if [ -s "$TMP" ]; then
-#   xsel -i -b < "$TMP"
-# else
-#   rm "$TMP"
-# fi
 
 isInteractive() {
 	ps -o stat= -p $$ | grep -q '+'
 }
 
-if isInteractive; then
-	unset VISUAL
-fi
+main() {
+	# TODO: arg to populate with PRIMARY clipboard
 
-echo | vipe 2> /dev/null | echo -n "$(cat)" | xsel -ib
+	# TMP=$(mktemp -p /tmp -t vimclip.XXXXXXXX)
+	# $EDITOR +"w! $TMP"
+	# if [ -s "$TMP" ]; then
+	#   xsel -i -b < "$TMP"
+	# else
+	#   rm "$TMP"
+	# fi
+
+	if isInteractive; then
+		unset VISUAL
+	fi
+
+	local output="$(echo | vipe 2> /dev/null)"
+
+	if [[ $output != "" ]]; then
+		echo -n "$output" | xsel -ib
+	fi
+}
+
+main "$@"
